"""usage table update

Revision ID: 66d97ed3bdc5
Revises: 9ecbd29ee907
Create Date: 2019-08-20 16:00:09.306326

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '66d97ed3bdc5'
down_revision = '9ecbd29ee907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_table', sa.Column(
        'channel_id', sa.VARCHAR(length=225), nullable=True))
    op.add_column('usage_table', sa.Column(
        'client_type', sa.VARCHAR(length=225), nullable=True))
    op.add_column('usage_table', sa.Column(
        'error_message', sa.VARCHAR(length=225), nullable=True))
    op.add_column('usage_table', sa.Column(
        'ethereum_json_rpc_endpoint', sa.VARCHAR(length=225), nullable=True))
    op.add_column('usage_table', sa.Column(
        'group_id', sa.VARCHAR(length=225), nullable=True))
    op.add_column('usage_table', sa.Column(
        'operation', sa.VARCHAR(length=225), nullable=True))
    op.add_column('usage_table', sa.Column(
        'org_id', sa.VARCHAR(length=225), nullable=True))
    op.add_column('usage_table', sa.Column(
        'registry_address_key', sa.VARCHAR(length=225), nullable=True))
    op.add_column('usage_table', sa.Column(
        'request_id', sa.VARCHAR(length=225), nullable=True))
    op.add_column('usage_table', sa.Column(
        'resource', sa.VARCHAR(length=225), nullable=True))
    op.add_column('usage_table', sa.Column(
        'response_code', sa.VARCHAR(length=225), nullable=True))
    op.add_column('usage_table', sa.Column(
        'response_time', sa.FLOAT(), nullable=True))
    op.add_column('usage_table', sa.Column(
        'user_address', sa.VARCHAR(length=225), nullable=True))
    op.add_column('usage_table', sa.Column(
        'user_details', sa.VARCHAR(length=225), nullable=True))
    op.add_column('usage_table', sa.Column(
        'username', sa.VARCHAR(length=225), nullable=True))
    op.add_column('usage_table', sa.Column(
        'version', sa.VARCHAR(length=225), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_table', 'version')
    op.drop_column('usage_table', 'username')
    op.drop_column('usage_table', 'user_details')
    op.drop_column('usage_table', 'user_address')
    op.drop_column('usage_table', 'response_time')
    op.drop_column('usage_table', 'response_code')
    op.drop_column('usage_table', 'resource')
    op.drop_column('usage_table', 'request_id')
    op.drop_column('usage_table', 'registry_address_key')
    op.drop_column('usage_table', 'org_id')
    op.drop_column('usage_table', 'operation')
    op.drop_column('usage_table', 'group_id')
    op.drop_column('usage_table', 'ethereum_json_rpc_endpoint')
    op.drop_column('usage_table', 'error_message')
    op.drop_column('usage_table', 'client_type')
    op.drop_column('usage_table', 'channel_id')
    # ### end Alembic commands ###
