"""added tables

Revision ID: 699f08a8834e
Revises: 
Create Date: 2019-08-07 22:55:12.604492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699f08a8834e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('service_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('free_calls', sa.Integer(), nullable=False),
    sa.Column('effective_start_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('effective_end_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_org_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group', sa.VARCHAR(length=32), nullable=True),
    sa.Column('org_name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('service_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('resource', sa.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_org_group_id', sa.Integer(), nullable=False),
    sa.Column('usage_type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('usage_value', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_org_group_id'], ['user_org_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_table')
    op.drop_table('user_org_group')
    op.drop_table('service_config')
    # ### end Alembic commands ###
