"""user address added

Revision ID: b0f9443a30de
Revises: 66d97ed3bdc5
Create Date: 2019-08-23 18:32:06.447515

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0f9443a30de'
down_revision = '66d97ed3bdc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_table', sa.Column('payment_mode', sa.VARCHAR(length=225), nullable=True))
    op.add_column('usage_table', sa.Column('service_id', sa.VARCHAR(length=225), nullable=True))
    op.add_column('user_org_group', sa.Column('user_address', sa.VARCHAR(length=225), nullable=True))
    op.alter_column('user_org_group', 'user_name',
                    existing_type=mysql.VARCHAR(length=225),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_org_group', 'user_name',
                    existing_type=mysql.VARCHAR(length=225),
                    nullable=False)
    op.drop_column('user_org_group', 'user_address')
    op.drop_column('usage_table', 'service_id')
    op.drop_column('usage_table', 'payment_mode')
    # ### end Alembic commands ###
